apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app 
        image: kathejagadeeshmzb/html-repo:latest
        ports:
        - containerPort: 80
