apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}    # The port that the service will expose
      targetPort: 80                      # The port on the container
      nodePort: {{ .Values.service.nodePort }}  # The port on each node that routes to the service
  type: NodePort

