image:
  repository: kathejagadeeshmzb/html-repo
  tag: latest

service:
  port: 80

ingress:
  enabled: true
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
