
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.docker_tag.outputs.TAG }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker tag
        id: docker_tag
        run: |
          TAG=${GITHUB_RUN_ID}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=TAG::$TAG"

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="kathejagadeeshmzb/html-repo"
          docker build -t $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }} .
          docker tag $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }}
          docker push $IMAGE_NAME:latest
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: check out code
        uses: actions/checkout@v3


      - name: apply kubernetes manifests
        run: |
          kubectl apply -f my-deployment.yaml || exit 1
          kubectl apply -f service.yaml || exit 1

      - name: update docker image to k3s
        env:
          IMAGE_NAME: "kathejagadeeshmzb/html-repo:${{ needs.build.outputs.image-tag }}"
        run: |
          kubectl get deployment my-deployment || exit 1
          kubectl set image deployment/my-deployment web-app=$IMAGE_NAME || exit 1
          kubectl rollout status deployment/my-deployment || exit 1
