name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.docker_tag.outputs.TAG }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker tag
        id: docker_tag
        run: |
          TAG=${GITHUB_RUN_ID}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=TAG::$TAG"

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="kathejagadeeshmzb/html-repo"
          docker build -t $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }} .
          docker tag $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.docker_tag.outputs.TAG }}
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
           mkdir -p $HOME/.kube
           echo "${KUBECONFIG}" | base64 -d > $HOME/.kube/config
           chmod 600 $HOME/.kube/config

      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm chart
        run: |
          cd my-chart  # Navigate to the directory containing your Helm chart
          helm package . --version ${{ needs.build.outputs.image-tag }}

      - name: Deploy with Helm
        env:
          IMAGE_NAME: "kathejagadeeshmzb/html-repo"
          IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
        run: |
          helm upgrade --install my-release ./my-chart --set image.repository=${IMAGE_NAME} --set image.tag=${IMAGE_TAG}